name: rnamodif_training_env
channels:
    - bioconda
    - conda-forge
    - pytorch
    - comet_ml
dependencies:
    - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
    - pytorch-lightning==1.7.0
    - cudatoolkit=11.3.1
    - numpy==1.22.0
    - torchmetrics==0.11.4
    - ont-fast5-api==4.1.1
    - scipy==1.9.0
    - scikit-learn==1.1.2
    - pandas==1.4.3
    - comet_ml==3.33.11
    - pip
    - pip:
        - -e ../../../../
