import os
from pathlib import Path
from dotenv import load_dotenv
import yaml

load_dotenv()
WANDB_API_KEY = os.getenv("WANDB_API_KEY") #Optional and used only for training

# LOAD CONFIG
if "--configfile" in sys.argv:
    i = sys.argv.index("--configfile")
    config_path = sys.argv[i + 1]
    configfile: config_path
else:
    config_path = "config/config.yml"
    configfile: config_path

with open(config["EXPS_CONFIG_FILE"], "r") as f:
    exp_config = yaml.safe_load(f)

config.update(exp_config)

REFERENCES_DIR = config['REFERENCES_DIR']
DATA_DIR = config['DATA_DIR']
OUTPUTS_DIR = config['OUTPUTS_DIR']
CHECKPOINTS_DIR = config['CHECKPOINTS_DIR']
HALFLIVES_FOLDER = config['HALFLIVES_FOLDER']
FASTA_TO_DOWNLOAD = config['FASTA_TO_DOWNLOAD']

BASE_EXPERIMENTS = config['EXPERIMENTS']
SPECIES_TO_GENOME = config['SPECIES_TO_GENOME']
SPECIES_TO_TRANSCRIPTOME = config['SPECIES_TO_TRANSCRIPTOME']

BASECALLING_CONFIG = config['BASECALLING_CONFIG']
REFERENCE_TO_SPLITS = config['REFERENCE_TO_SPLITS']
TRAINING_CONFIGS = config['TRAINING_CONFIGS']
MODEL_TO_PATH = config['MODEL_TO_PATH']
MODEL_INFERENCE_PARAMS = config['MODEL_INFERENCE_PARAMS']
INFERENCE_RUN_GROUPS = config['INFERENCE_RUN_GROUPS']
ENSEMBL_URL = config['ENSEMBL_URL']
HALFLIVES_NAME_TO_FILE = config['HALFLIVES_NAME_TO_FILE']
GPUS_FOR_RULES = config['GPUS_FOR_RULES']
PCT_POS_GRAPHING_PARAMS = config["PCT_POS_GRAPHING_PARAMS"]
DIAGNOSTICS_GRAPHING_PARAMS = config["DIAGNOSTICS_GRAPHING_PARAMS"]

SPLIT_EXPERIMENTS = {}
for exp_name, exp_data in BASE_EXPERIMENTS.items():
    for split in ("TEST", "TRAINING", "VALIDATION"):
        SPLIT_EXPERIMENTS[f"{exp_name}_{split}"] = {
            **exp_data,
            "path": f"../{OUTPUTS_DIR}/splits/{exp_name}/{split.lower()}.pod5",
            "base_experiment": exp_name,
            "split": split.lower(), }

EXPERIMENTS = {**BASE_EXPERIMENTS, **SPLIT_EXPERIMENTS}

# RULES
include: "rules/basecalling.smk"
include: "rules/alignment.smk"
include: "rules/data_split.smk"
include: "rules/training.smk"
include: "rules/inference.smk"
include: "rules/visualizations.smk"
include: "rules/halflives.smk"
include: "rules/diagnostics.smk"

rule all:
    input:
        expand('outputs/full_exp_predictions_pct_pos/{model_name}/{experiment_name}_percent_positive.txt', model_name="R10_4SU_1", experiment_name=config["ALL_EXPERIMENTS"]),
        expand('outputs/full_exp_predictions/{model_name}/{experiment_name}/preds.csv', model_name=['R10_4SU_1', 'R10_4SU_Gruenebast', 'R10_4SU_2'], experiment_name=ALL_EXPERIMENTS),
        expand('outputs/R10_exp_predictions/{model_name}/{experiment_name}/preds.csv', model_name=['R10_4SU_1', 'R10_4SU_Gruenebast', 'R10_4SU_2'], experiment_name=config['ALL_R10_EXPERIMENTS']),
        'outputs/visual/pct_pos/4SU_models_comparison.png',
        expand('outputs/visual/predictions/{model_name}/{group}_{plot_type}.pdf', 
                model_name=['R10_4SU_1', 'R10_4SU_Gruenebast', 'R10_4SU_2.2',  'R10_4SU_3_Gruenebast'],
                group=list(INFERENCE_RUN_GROUPS.keys()), plot_type=['auroc','thresholds','pr_curve','pr_ratios']),

        expand('outputs/full_exp_predictions/{model_name}/{experiment_name}/preds.csv',
                 model_name=['R10_4SU_1', 'R10_4SU_Gruenebast', 'R10_4SU_2.2', 'R10_4SU_3_Gruenebast'],
                 experiment_name='20260519_mmu_dRNA_3T3_4SU_2h_1'),

        expand('outputs/visual/predictions/{model_name}/{experiment_name}/decay/{halflives_name}_halflives_{reference_level}_read_limit_decay_plot.pdf',
                model_name=['R10_4SU_1', 'R10_4SU_Gruenebast', 'R10_4SU_2.2',  'R10_4SU_3_Gruenebast'],
                experiment_name='20260519_mmu_dRNA_3T3_4SU_2h_1',
                halflives_name=['mion','PION'],
                reference_level=['gene','transcript']),
        # 'checkpoints_pl/R10_mega_model_1/DONE.txt',