import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# DATA PREPARATION CONFIGURATION
#TODO refactor genome/transcriptome URLs to be automatically constructed
fasta_to_download = {
    'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz',
    'Homo_sapiens.GRCh38.cdna.all.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz',
    
    'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa':'https://ftp.ensembl.org/pub/release-114/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz',
    'Mus_musculus.GRCm39.cdna.all.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz',
}

exp_to_reference = {
    '20250529_hsa_dRNA_HeLa_5EU_1':       'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250529_hsa_dRNA_HeLa_DMSO_1':      'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250529_hsa_dRNA_Hek293_5EU_1':     'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250529_hsa_dRNA_Hek293_DMSO_1':    'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250612_hsa_dRNA_MCF10A_5EU_1':     'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250612_hsa_dRNA_MCF10A_control_1': 'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250618_hsa_dRNA_I90_5EU_1':        'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250612_hsa_dRNA_I90_control_1':    'references/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',

    '20250528_mmu_dRNA_3T3_5EU_1':  'references/fasta/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa',
    '20250528_mmu_dRNA_3T3_DMSO_1': 'references/fasta/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa',

    #TODO Macaca mulatta? primary_assembly on ensembl is shattered to separate chromosomes, not a single file
    # '20250611_mml_dRNA_PBMC_5EU_1':,
    # '20250612_mml_dRNA_PBMC_control_1':,
}
exp_to_transcriptome = {
    '20250529_hsa_dRNA_HeLa_5EU_1':'references/fasta/Homo_sapiens.GRCh38.cdna.all.fa',

    '20250528_mmu_dRNA_3T3_5EU_1':  'references/fasta/Mus_musculus.GRCm39.cdna.all.fa',
    '20250528_mmu_dRNA_3T3_DMSO_1': 'references/fasta/Mus_musculus.GRCm39.cdna.all.fa',
}
exp_to_path = {
    '20250529_hsa_dRNA_HeLa_5EU_1':'/home/jovyan/data/experiments/20250529_hsa_dRNA_HeLa_5EU_1/',
    '20250529_hsa_dRNA_HeLa_DMSO_1':'/home/jovyan/data/experiments/20250529_hsa_dRNA_HeLa_DMSO_1/',

    '20250529_hsa_dRNA_Hek293_5EU_1':'/home/jovyan/data/experiments/20250529_hsa_dRNA_Hek293_5EU_1',
    '20250529_hsa_dRNA_Hek293_DMSO_1':'/home/jovyan/data/experiments/20250529_hsa_dRNA_Hek293_DMSO_1',

    '20250611_mml_dRNA_PBMC_5EU_1':'/home/jovyan/data/experiments/20250611_mml_dRNA_PBMC_5EU_1',
    '20250612_mml_dRNA_PBMC_control_1':'/home/jovyan/data/experiments/20250612_mml_dRNA_PBMC_control_1',

    '20250618_hsa_dRNA_I90_5EU_1':'/home/jovyan/data/experiments/20250618_hsa_dRNA_I90_5EU_1',
    '20250612_hsa_dRNA_I90_control_1':'/home/jovyan/data/experiments/20250612_hsa_dRNA_I90_control_1',

    '20250612_hsa_dRNA_MCF10A_5EU_1':'/home/jovyan/data/experiments/20250612_hsa_dRNA_MCF10A_5EU_1',
    '20250612_hsa_dRNA_MCF10A_control_1':'/home/jovyan/data/experiments/20250612_hsa_dRNA_MCF10A_control_1',

    '20250528_mmu_dRNA_3T3_5EU_1':'/home/jovyan/data/experiments/20250528_mmu_dRNA_3T3_5EU_1',
    '20250528_mmu_dRNA_3T3_DMSO_1':'/home/jovyan/data/experiments/20250528_mmu_dRNA_3T3_DMSO_1',
}
basecalling_config = {
    'dorado_version':'dorado-1.0.1-linux-x64', # versions: https://dorado-docs.readthedocs.io/en/latest/
    'basecalling_model':'rna004_130bps_hac@v5.2.0',
}
train_chrs=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,'X','MT']
test_chrs=[1]
valid_chrs=[20]

# TRAINING CONFIGURATIONS
training_configs  = {
    'Hela_batch_64': {
        'training_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1'],
        'training_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1'],
        'validation_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1'], #Same experiment, but will take reads from a different chromosome
        'validation_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1'],
        'min_len':5000,
        'max_len':400000,
        'skip':5000,
        'workers':32,
        'batch_size':64,
        'sampler':'ratio', #sample from experiments based on their size, alternative 'uniform' for uniform sampling
        'lr':1e-4,
        'warmup_steps':100,
        'wd':0.01,
        'arch':'rnakinet', #'rnakinet' (default) or 'rnakinet_lastonly' (different rnn pooling method)
        'arch_hyperparams':{},
        'grad_acc':1,
        'early_stopping_patience':150, 
        'wandb_api_key':os.getenv("WANDB_API_KEY"), #OPTIONAL: Set your wandb API key for plotting training metrics
        'wandb_project_name':'RNAkinet',
        'logging_step':500,
        'enable_progress_bar':'yes', #set to yes if you want to log training progress bar
        'log_to_file':False, #set to False if you want to log to console, otherwise logged to checkpoints_pl folder
        'valid_read_limit':5000,
    },
    'Hela_batch_32_more_fast_2': {
        'training_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_Hek293_5EU_1', '20250612_hsa_dRNA_MCF10A_5EU_1', '20250618_hsa_dRNA_I90_5EU_1'],
        'training_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1', '20250529_hsa_dRNA_Hek293_DMSO_1', '20250612_hsa_dRNA_MCF10A_control_1','20250612_hsa_dRNA_I90_control_1'],
        'validation_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_Hek293_5EU_1', '20250612_hsa_dRNA_MCF10A_5EU_1', '20250618_hsa_dRNA_I90_5EU_1'],
        'validation_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1', '20250529_hsa_dRNA_Hek293_DMSO_1', '20250612_hsa_dRNA_MCF10A_control_1','20250612_hsa_dRNA_I90_control_1'],
        'min_len':5000,
        'max_len':400000,
        'skip':5000,
        'workers':32,
        'batch_size':32,
        'sampler':'ratio', #sample from experiments based on their size, alternative 'uniform' for uniform sampling
        'lr':1e-3,
        'warmup_steps':100,
        'wd':0.01,
        'arch':'rnakinet', #'rnakinet' (default) or 'rnakinet_lastonly' (different rnn pooling method)
        'arch_hyperparams':{},
        'grad_acc':1,
        'early_stopping_patience':100, 
        'wandb_api_key':os.getenv("WANDB_API_KEY"), #OPTIONAL: Set your wandb API key for plotting training metrics
        'wandb_project_name':'RNAkinet',
        'logging_step':5000,
        'enable_progress_bar':'yes', #set to yes if you want to log training progress bar
        'log_to_file':False, #set to False if you want to log to console, otherwise logged to checkpoints_pl folder
        'valid_read_limit':5000,
    },
}

# INFERENCE AND VISUALIZATION CONFIGURATION (POST-TRAINING)
model_to_path = {
    'test_2': 'checkpoints_pl/test_run_2/last.ckpt',
    'HeLa_batch_32': 'checkpoints_pl/test_run_4/best-step=175000-valid_loss=0.29.ckpt',
    'Hela_batch_64': 'checkpoints_pl/Hela_batch_64/best-step=1271000-valid_loss=0.25.ckpt',
}
model_inference_params = {
    'test_2': {
        'batch_size': 1,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'rnakinet',
        'threshold': 0.5,
    },
    'HeLa_batch_32': {
        'batch_size': 32,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'rnakinet',
        'threshold': 0.5,
    },
    'Hela_batch_64': {
        'batch_size': 64,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'rnakinet',
        'threshold': 0.5,
    },
}
inference_run_to_files = {
    '20250529_hsa_dRNA_HeLa_5EU_1_TEST': ['outputs/splits/20250529_hsa_dRNA_HeLa_5EU_1/test.pod5'],
    '20250529_hsa_dRNA_HeLa_DMSO_1_TEST': ['outputs/splits/20250529_hsa_dRNA_HeLa_DMSO_1/test.pod5'],

    '20250528_mmu_dRNA_3T3_5EU_1':Path('/home/jovyan/data/experiments/20250528_mmu_dRNA_3T3_5EU_1').rglob("*.pod5"),
    '20250528_mmu_dRNA_3T3_DMSO_1':Path('/home/jovyan/data/experiments/20250528_mmu_dRNA_3T3_DMSO_1').rglob("*.pod5"),
}
inference_run_groups = {
    'HeLa_NIH_2025':{
        'positives':['20250529_hsa_dRNA_HeLa_5EU_1_TEST'],
        'negatives':['20250529_hsa_dRNA_HeLa_DMSO_1_TEST'],
    },
}

# HALFLIVES CONFIGURATION
ENSEMBL_URL = 'http://may2025.archive.ensembl.org'
exp_to_ensembl_species = {
    '20250528_mmu_dRNA_3T3_5EU_1':'mmusculus',
    '20250528_mmu_dRNA_3T3_DMSO_1': 'mmusculus',
}

# RULES
include: "rules/basecalling.smk"
include: "rules/alignment.smk"
include: "rules/data_split.smk"
include: "rules/training.smk"
include: "rules/inference.smk"
include: "rules/visualizations.smk"
include: "rules/halflives.smk"


rule all:
    input:
        #expand('outputs/basecalling/{experiment_name}/{dorado_version}/{basecalling_model}/DONE.txt',experiment_name=exp_to_path.keys(),dorado_version=basecalling_config['dorado_version'],basecalling_model=basecalling_config['basecalling_model'])
        #expand('outputs/visual/predictions/{model_name}/{group}_{plot_type}.pdf', model_name='Hela_batch_64', group='HeLa_NIH_2025', plot_type=['auroc','thresholds','pr_curve','pr_ratios'])
        #expand('outputs/{model_name}/{experiment_name}/preds.csv',model_name='test_2', experiment_name=['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_HeLa_DMSO_1'])
        #expand("outputs/splits/{experiment_name}/{split}.pod5", experiment_name=['20250529_hsa_dRNA_HeLa_5EU_1','20250529_hsa_dRNA_HeLa_DMSO_1'], split=['train','validation','test'])
        # expand('checkpoints_pl/{training_run_name}/DONE.txt', training_run_name='Hela_batch_32_more_fast_2')
        # expand("outputs/alignment/{experiment_name}/{dorado_version}/{basecalling_model}/reads-align.transcriptome.sorted.bam.bai", experiment_name='20250529_hsa_dRNA_HeLa_5EU_1',dorado_version=basecalling_config['dorado_version'],basecalling_model=basecalling_config['basecalling_model'])
        # expand("references/{species_id}/transcript-gene-ids.tab", species_id='hsapiens')
        expand('outputs/predictions/{model_name}/{experiment_name}/gene_level_predictions.tsv', model_name='Hela_batch_64', experiment_name='20250528_mmu_dRNA_3T3_5EU_1')
        # 'outputs/alignment/20250528_mmu_dRNA_3T3_5EU_1/reads-align.transcriptome.sorted.bam'
        


        