#TODO extract
exp_to_reference = {
    'exp1': 'references/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
}
train_chrs=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,'X','MT']
test_chrs=[1]
valid_chrs=[20]

include: "rules/basecalling.smk"
include: "rules/alignment.smk"
include: "rules/data_split.smk"

#versions: https://dorado-docs.readthedocs.io/en/latest/
# dorado-1.0.1-linux-x64
# rna004_130bps_hac@v5.0.1

rule all:
    input:
        # expand('checkpoints_pl/{training_experiment_name}/DONE.txt', training_experiment_name='test_run')
        # expand('dorado-1.0.1-linux-arm64/bin/dorado')
        # expand('outputs/basecalling/exp1/DONE_dorado.txt')
        # expand('outputs/basecalling/exp1/dorado/all_reads.fastq.gz')
        # expand("outputs/alignment/exp1/reads-align.genome.sorted.bam")
        # expand("outputs/splits/exp1/train_readids.txt")
        