#Basecalling information
BASECALLER_VERSION : 'ont-guppy_6.4.8_linux64'

EXPERIMENT_NAME_TO_PATH : {
    '20220520_hsa_dRNA_HeLa_DMSO_1': 'local_store/store/seq/ont/experiments/20220520_hsa_dRNA_HeLa_DMSO_1',
    '20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2': 'local_store/store/seq/ont/experiments/20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2',
    
    '20201016_hsa_dRNASeq_HeLa_dmso_polyA_REL5_short_1': 'local_store/store/seq/ont/experiments/20201016_hsa_dRNASeq_HeLa_dmso_polyA_REL5_short_1',
    '20201016_hsa_dRNASeq_HeLa_5EU_polyA_REL5_short_1': 'local_store/store/seq/ont/experiments/20201016_hsa_dRNASeq_HeLa_5EU_polyA_REL5_short_1',

    '20180327_1102_K562_5EU_0_unlabeled_run': 'local_store/nanoid/20180327_1102_K562_5EU_0_unlabeled_run',
    '20180403_1102_K562_5EU_0_unlabeled_II_run': 'local_store/nanoid/20180403_1102_K562_5EU_0_unlabeled_II_run',
    '20180403_1208_K562_5EU_0_unlabeled_III_run': 'local_store/nanoid/20180403_1208_K562_5EU_0_unlabeled_III_run',
    '20180514_1054_K562_5EU_1440_labeled_run': 'local_store/nanoid/20180514_1054_K562_5EU_1440_labeled_run',
    '20180514_1541_K562_5EU_1440_labeled_II_run': 'local_store/nanoid/20180514_1541_K562_5EU_1440_labeled_II_run',
    '20180516_1108_K562_5EU_1440_labeled_III_run': 'local_store/nanoid/20180516_1108_K562_5EU_1440_labeled_III_run',
    
    '20201001_hsa_dRNA_Hek293T_NoArs_5P_1': 'local_store/arsenite/raw/20201001_hsa_dRNA_Hek293T_NoArs_5P_1',
    '20201022_hsa_dRNA_Neuron_ctrl_5P_1': 'local_store/arsenite/raw/20201022_hsa_dRNA_Neuron_ctrl_5P_1',
    '20201022_hsa_dRNA_Neuron_TDP_5P_1': 'local_store/arsenite/raw/20201022_hsa_dRNA_Neuron_TDP_5P_1',
    
    
    '20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1': 'local_store/arsenite/raw/20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1',
    '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2': 'local_store/arsenite/raw/20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2',
    '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3': 'local_store/arsenite/raw/20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3',
    
    '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1': 'local_store/arsenite/raw/20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1',
    '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2': 'local_store/arsenite/raw/20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2',
    # 'noars_0030_3':,
    
    '20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1': 'local_store/arsenite/raw/20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1',
    '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_2': 'local_store/arsenite/raw/20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_2',
    '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3': 'local_store/arsenite/raw/20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3',
    
    '20201215_hsa_dRNA_HeLa_5EU_2hr_Ars_0060m_5P_1': 'local_store/arsenite/raw/20201215_hsa_dRNA_HeLa_5EU_2hr_Ars_0060m_5P_1',
    '20210202_hsa_dRNA_HeLa_5EU_2hr_Ars_0060m_5P_2': 'local_store/arsenite/raw/20210202_hsa_dRNA_HeLa_5EU_2hr_Ars_0060m_5P_2',
    '20210519_hsa_dRNA_HeLa_5EU_2hr_Ars_0060m_5P_3': 'local_store/arsenite/raw/20210519_hsa_dRNA_HeLa_5EU_2hr_Ars_0060m_5P_3',
    
    '20210111_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_1': 'local_store/arsenite/raw/20210111_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_1',
    '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_2': 'local_store/arsenite/raw/20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_2',
    '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_3': 'local_store/arsenite/raw/20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_3',
    
    '20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_1': 'local_store/arsenite/raw/20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_1',
    '20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_2': 'local_store/arsenite/raw/20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_2',
    # 'noars_0120_3':,
    
    '20210114_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_1': 'local_store/arsenite/raw/20210114_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_1',
    '20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_2': 'local_store/arsenite/raw/20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_2',
    # 'noars_0180_3':,
    
    '20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0300m_5P_1': 'local_store/arsenite/raw/20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0300m_5P_1',
    # 'noars_0300_2':,
    # 'noars_0300_3':,
    
    
    
    
    '20180327_1102_K562_5EU_0_unlabeled_run_TEST': 'outputs/splits/20180327_1102_K562_5EU_0_unlabeled_run/test',
    '20180514_1054_K562_5EU_1440_labeled_run_TEST': 'outputs/splits/20180514_1054_K562_5EU_1440_labeled_run/test',
    
    '20180403_1102_K562_5EU_0_unlabeled_II_run_TEST': 'outputs/splits/20180403_1102_K562_5EU_0_unlabeled_II_run/test',
    '20180514_1541_K562_5EU_1440_labeled_II_run_TEST': 'outputs/splits/20180514_1541_K562_5EU_1440_labeled_II_run/test',
    
    '20180403_1208_K562_5EU_0_unlabeled_III_run_TEST': 'outputs/splits/20180403_1208_K562_5EU_0_unlabeled_III_run/test',
    '20180516_1108_K562_5EU_1440_labeled_III_run_TEST': 'outputs/splits/20180516_1108_K562_5EU_1440_labeled_III_run/test',
    
    '20201016_hsa_dRNASeq_HeLa_dmso_polyA_REL5_short_1_TEST': 'outputs/splits/20201016_hsa_dRNASeq_HeLa_dmso_polyA_REL5_short_1/test',
    '20201016_hsa_dRNASeq_HeLa_5EU_polyA_REL5_short_1_TEST': 'outputs/splits/20201016_hsa_dRNASeq_HeLa_5EU_polyA_REL5_short_1/test',
    
    '20220520_hsa_dRNA_HeLa_DMSO_1_TEST': 'outputs/splits/20220520_hsa_dRNA_HeLa_DMSO_1/test',
    '20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2_TEST': 'outputs/splits/20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2/test',
    
}

#TODO check if the experiment has kit when theres no explicit basecalls - throws an keyerror
KITS : {
    '20220520_hsa_dRNA_HeLa_DMSO_1': 'SQK-RNA002',
    '20220520_hsa_dRNA_HeLa_DMSO_1': 'SQK-RNA002',
    '20201016_hsa_dRNASeq_HeLa_dmso_polyA_REL5_short_1': 'SQK-RNA002',
    '20201016_hsa_dRNASeq_HeLa_5EU_polyA_REL5_short_1': 'SQK-RNA002',
    
    '20180327_1102_K562_5EU_0_unlabeled_run': 'SQK-RNA001',
    '20180403_1102_K562_5EU_0_unlabeled_II_run': 'SQK-RNA001',
    '20180403_1208_K562_5EU_0_unlabeled_III_run': 'SQK-RNA001',
    
    '20180514_1054_K562_5EU_1440_labeled_run': 'SQK-RNA001',
    '20180514_1541_K562_5EU_1440_labeled_II_run': 'SQK-RNA001',
    '20180516_1108_K562_5EU_1440_labeled_III_run': 'SQK-RNA001',
    #Include kits for different experiments
    #TODO add flowcells also? (neuron data have different flowcell)
    
    '20180327_1102_K562_5EU_0_unlabeled_run_TEST': 'SQK-RNA001',
    '20180403_1102_K562_5EU_0_unlabeled_II_run_TEST': 'SQK-RNA001',
    '20180403_1208_K562_5EU_0_unlabeled_III_run_TEST': 'SQK-RNA001',
    '20180514_1054_K562_5EU_1440_labeled_run_TEST': 'SQK-RNA001',
    '20180514_1541_K562_5EU_1440_labeled_II_run_TEST': 'SQK-RNA001',
    '20180516_1108_K562_5EU_1440_labeled_III_run_TEST': 'SQK-RNA001',
    
    '20220520_hsa_dRNA_HeLa_DMSO_1_TEST': 'SQK-RNA002',
    '20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2_TEST': 'SQK-RNA002',
    
}




# Mapping information
HUMAN_REF_VERSION : 'Homo_sapiens.GRCh38.dna_sm.primary_assembly'
HUMAN_TRANSCRIPTOME_VERSION : 'Homo_sapiens.GRCh38.cdna.all'


# Use for specifying basecalls explicitly, for example if you dont want to run HAC basecalling or you have basecalls already
# EXPLICIT_BASECALL_PATHS: {
#     '20201001_hsa_dRNA_Hek293T_NoArs_5P_1': 'local_store/arsenite/raw/20201001_hsa_dRNA_Hek293T_NoArs_5P_1/guppy/reads.fastq.gz',
#     '20201022_hsa_dRNA_Neuron_ctrl_5P_1': 'local_store/arsenite/raw/20201022_hsa_dRNA_Neuron_ctrl_5P_1/guppy/reads.fastq.gz',
#     '20201022_hsa_dRNA_Neuron_TDP_5P_1': 'local_store/arsenite/raw/20201022_hsa_dRNA_Neuron_TDP_5P_1/guppy/reads.fastq.gz',
    
#     '20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1': 'local_store/arsenite/raw/20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1/guppy/reads.fastq.gz',
#     '20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1': 'local_store/arsenite/raw/20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1/guppy/reads.fastq.gz',
    
#     '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2': 'local_store/arsenite/raw/20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2/guppy/reads.fastq.gz',
    
#     '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3': 'local_store/arsenite/raw/20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3/guppy/reads.fastq.gz',
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3': 'local_store/arsenite/raw/20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3/guppy/reads.fastq.gz',
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_3': 'local_store/arsenite/raw/20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_3/guppy/reads.fastq.gz',
    
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3': 'local_store/arsenite/raw/20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3/guppy/reads.fastq.gz',
#     '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1': 'local_store/arsenite/raw/20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1/guppy/reads.fastq.gz',
#     '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2': 'local_store/arsenite/raw/20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2/guppy/reads.fastq.gz',
    
    
#     # '20180327_1102_K562_5EU_0_unlabeled_run_TEST': 'outputs/basecalling/20180327_1102_K562_5EU_0_unlabeled_run/guppy/reads.fastq.gz',
#     # '20180514_1054_K562_5EU_1440_labeled_run_TEST': 'outputs/basecalling/20180514_1054_K562_5EU_1440_labeled_run/guppy/reads.fastq.gz',
#     # '20220520_hsa_dRNA_HeLa_DMSO_1_TEST': 'outputs/basecalling/20220520_hsa_dRNA_HeLa_DMSO_1/guppy/reads.fastq.gz',
#     # '20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2_TEST': 'outputs/basecalling/20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2/guppy/reads.fastq.gz',
# }

# Splitting information
default_train_chrs: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,'X','MT']
default_test_chrs: [1]
default_validation_chrs: []

EXPLICIT_SPLITS: {
    '20220520_hsa_dRNA_HeLa_DMSO_1': {
        'train': [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,'X','MT'],
        'test': [1],
        'validation': [20],
    },
    '20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2': {
        'train': [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,'X','MT'],
        'test': [1],
        'validation': [20],
    },
}


# Inference information
MODELS: {
    'narrow_weighted':{
        'path':'checkpoints_pl/5eu_2022_gru32_weighted02/last-Copy1.ckpt',
        'window': 4096,
        'weighted': True,
     },
    'narrow_standard':{
        'path':'checkpoints_pl/5eu_2022_unfrozen_gru32_lowLR/last-Copy1.ckpt',
        'window': 4096,
        'weighted': False,
    },
    'wide_standard':{
        'path':'checkpoints_pl/2022_wide/last-Copy1.ckpt',
        'window': 40960,
        'weighted': False,
    },
    'wide_weighted':{
        'path':'checkpoints_pl/2022_wide_weighted02/last-Copy1.ckpt',
        'window': 40960,
        'weighted': True,
    },
    'unlimited_standard_allneg':{
        'path':'checkpoints_pl/2022_uncut_allneg/last-Copy1_8624step.ckpt',
        'window': null, #model with unlimited window
        'weighted': False,
        'threshold': 0.75,
        
    },
    'unlimited_standard_2022neuronctrl':{
        'path':'checkpoints_pl/2022_uncut_neg2022+neuronctrl/epoch=0-step=1625-Copy1.ckpt',
        'window': null,
        'weighted': False,
    },
    'unlimited_allneg_maxpool':{
        'path':'checkpoints_pl/2022_uncut_allneg_maxpool/epoch=0-step=1875-Copy1.ckpt',
        'window': null,
        'weighted': False,
    },
    'CUSTOM_allneg_maxpool':{
        'path':'checkpoints_pl/2022_mine_allneg/last-Copy5.ckpt',
        'window': null,
        'weighted': False,
        'threshold': 0.5,
        
    },
    'CUSTOM_maxpool':{
        'path':'checkpoints_pl/2022_mine/last.ckpt',
        'window': null,
        'weighted': False,
    },
}

LIMITED_INFERENCE_FILE_LIMIT: 5
INFERENCE_BATCH_SIZE: 1

#Visuals

#Violins
# PREDICTION_TYPE : 'predictions_limited'
# POOLING : 'mean'

#Aurocs
# PLOT_NEG_POS_PAIRS: [
    # ['20220520_hsa_dRNA_HeLa_DMSO_1','20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2'],
    # ['20201016_hsa_dRNASeq_HeLa_dmso_polyA_REL5_short_1','20201016_hsa_dRNASeq_HeLa_5EU_polyA_REL5_short_1'],
    # ['20180327_1102_K562_5EU_0_unlabeled_run','20180514_1054_K562_5EU_1440_labeled_run'],
    # ['20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1','20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1'],
    # ['20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3','20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_2'],
    
    # ['20220520_hsa_dRNA_HeLa_DMSO_1_TEST','20220303_hsa_dRNA_HeLa_5EU_polyA_REL5_2_TEST'],
    # ['20180327_1102_K562_5EU_0_unlabeled_run_TEST','20180514_1054_K562_5EU_1440_labeled_run_TEST'],
    
# ]
# PLOT_TYPES : ['auroc', 'thresholds', 'pr_curve']

# PLOT_TYPES : ['auroc', 'thresholds', 'pr_curve']
# PLOT_TYPES : ['chr_acc']
# PLOT_TYPES : ['violin']



# CHR_PLOT_NEG_POS_PAIR : ['20180327_1102_K562_5EU_0_unlabeled_run_TEST','20180514_1054_K562_5EU_1440_labeled_run_TEST']

# models to run the commands for
# MODELS_TO_PROCESS : ['narrow_weighted','narrow_standard','wide_standard','wide_weighted','unlimited_standard_allneg','unlimited_standard_2022neuronctrl','unlimited_allneg_maxpool', 'CUSTOM_allneg_maxpool']
# MODELS_TO_PROCESS : ['CUSTOM_allneg_maxpool', 'CUSTOM_maxpool']


# PLOT_NAME : 'arsSP3_FIN'

# EXPERIMENTS_TO_PROCESS : [
#     '20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1', 
#     '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1', 
#     '20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1', 
#     '20210111_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_1', 
#     '20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_1', 
#     '20210114_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_1', 
#     '20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0300m_5P_1',
# ]

# EXPERIMENTS_TO_PROCESS : [
#     '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2',
#     '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2',
#     '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_2', 
#     '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_2', 
#     '20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_2',
#     '20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_2',
# ]

# EXPERIMENTS_TO_PROCESS : [
#     '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3',
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3',
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_3',
# ]

# EXPERIMENTS_TO_PROCESS : [
#     '20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1', 
#     '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1', 
#     '20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1', 
#     '20210111_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_1', 
#     '20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_1', 
#     '20210114_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_1', 
#     '20201220_hsa_dRNA_HeLa_5EU_2hr_NoArs_0300m_5P_1',
#     '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2',
#     '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2',
#     '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_2', 
#     '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_2', 
#     '20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0120m_5P_2',
#     '20210205_hsa_dRNA_HeLa_5EU_2hr_NoArs_0180m_5P_2',
#     '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3',
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3',
#     '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0090m_5P_3',
# ]

# TIMEPOINTS: {
#     '0m' : [
#         '20210111_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_1', 
#         '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_2',
#         '20210208_hsa_dRNA_HeLa_5EU_1hr_ctrl_0000m_5P_3',

#         '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3',
#         '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_1', 
#         '20210128_hsa_dRNA_HeLa_5EU_2hr_NoArs_0030m_5P_2',
        
#         # '20201215_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_1', 
#         # '20210202_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_2',
#         # '20210519_hsa_dRNA_HeLa_5EU_2hr_NoArs_0060m_5P_3',
        
        
#     ]
# }
