from pathlib import Path

configfile: "config.yml"

include: "rules/basecalling.smk"
include: "rules/alignment.smk"
include: "rules/data_split.smk"
include: "rules/inference.smk"


rule all:
    input:
        expand('outputs/predictions_limited/{model_name}/{experiment_name}/mean_pooling.pickle', experiment_name=config['EXPERIMENTS_TO_PROCESS'], model_name=config['MODELS_TO_PROCESS'])

# snakemake --cores 1 --rerun-incomplete --use-conda