REFERENCES_DIR: "references"
DATA_DIR: "data"
OUTPUTS_DIR: "outputs"
CHECKPOINTS_DIR: "checkpoints_pl"
HALFLIVES_FOLDER: "halflives_data"
EXPS_CONFIG_FILE: "config/experiments.yml"

# DATA PREPARATION CONFIGURATION
FASTA_TO_DOWNLOAD: {
    # human
    'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz',
    'Homo_sapiens.GRCh38.cdna.all.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz',
    # mouse
    'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz',
    'Mus_musculus.GRCm39.cdna.all.fa': 'https://ftp.ensembl.org/pub/release-114/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz',
    # yeast
    'Saccharomyces_cerevisiae.R64-1-1.dna_sm.toplevel.fa': 'https://ftp.ensembl.org/pub/release-115/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna_sm.toplevel.fa.gz',
}

BASECALLING_CONFIG : {
    'dorado_version':'dorado-1.0.1-linux-x64', # versions: https://dorado-docs.readthedocs.io/en/latest/
    'basecalling_model':'rna004_130bps_hac@v5.2.0',
}

GPUS_FOR_RULES : {
    'basecalling_dorado' : {
        'gpu' : 2,
        'gpu_model' : "[gpuv100x|gpua100]",
    },
    'inference_rnakinet' : {
        'gpu' : 1,
        'gpu_model' : "[gpuv100x|gpua100]",
    },
    'run_training' : {
        'gpu' : 2,
        'gpu_model' : "[gpuv100x|gpua100]",
    }
}
REFERENCE_TO_SPLITS : {
    'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa': {
        'train_chrs':[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,'X','MT'],
        'test_chrs':[1],
        'valid_chrs':[20],
    },
    'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa': {
        'train_chrs':[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,'X','MT'],
        'test_chrs':[1],
        'valid_chrs':[19],
    },
    'Saccharomyces_cerevisiae.R64-1-1.dna_sm.toplevel.fa': {
        'train_chrs': ['I', 'II', 'III', 'V', 'VI', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'Mito'],
        'test_chrs': ['IV'],
        'valid_chrs': ['VII']
    }
}

# TRAINING CONFIGURATIONS
TRAINING_CONFIGS : {
    'Hela_batch_64': {
        'training_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1'],
        'training_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1'],
        'validation_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1'], #Same experiment, but will take reads from a different chromosome
        'validation_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1'],
        'min_len':5000,
        'max_len':400000,
        'skip':5000,
        'workers':32,
        'batch_size':64,
        'sampler':'ratio', #sample from experiments based on their size, alternative 'uniform' for uniform sampling
        'lr':1e-4,
        'warmup_steps':100,
        'wd':0.01,
        'arch':'v2.0', #uses the name-to-architecture mapper in rnakinet/models/model_loader.py
        'arch_hyperparams':{},
        'grad_acc':1,
        'early_stopping_patience':150, 
        'wandb_project_name':'RNAkinet',
        'logging_step':500,
        'enable_progress_bar':'yes', #set to yes if you want to log training progress bar
        'log_to_file':False, #set to False if you want to log to console, otherwise logged to checkpoints_pl folder
        'valid_read_limit':5000,
    },
    'Human_batch_64_uniform': {
        'training_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_Hek293_5EU_1', '20250612_hsa_dRNA_MCF10A_5EU_1', '20250618_hsa_dRNA_I90_5EU_1'],
        'training_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1', '20250529_hsa_dRNA_Hek293_DMSO_1', '20250612_hsa_dRNA_MCF10A_control_1','20250612_hsa_dRNA_I90_control_1'],
        'validation_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_Hek293_5EU_1', '20250612_hsa_dRNA_MCF10A_5EU_1', '20250618_hsa_dRNA_I90_5EU_1'],
        'validation_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1', '20250529_hsa_dRNA_Hek293_DMSO_1', '20250612_hsa_dRNA_MCF10A_control_1','20250612_hsa_dRNA_I90_control_1'],
        'min_len':5000,
        'max_len':400000,
        'skip':5000,
        'workers':32,
        'batch_size':64,
        'sampler':'uniform',
        'lr':1e-4,
        'warmup_steps':100,
        'wd':0.01,
        'arch':'v2.0',
        'arch_hyperparams':{},
        'grad_acc':1,
        'early_stopping_patience':200, 
        'wandb_project_name':'RNAkinet',
        'logging_step':10000,
        'enable_progress_bar':'no', 
        'log_to_file':False,
        'valid_read_limit':5000,
    },
    'rnakinet_dev_test': {
        'training_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1'],
        'training_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1'],
        'validation_positives_exps': ['20250529_hsa_dRNA_HeLa_5EU_1'],
        'validation_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1'],
        'min_len':5000,
        'max_len':100000,
        'skip':5000,
        'workers':32,
        'batch_size':64,
        'sampler':'uniform', #sample from experiments based on their size, alternative 'uniform' for uniform sampling
        'lr':1e-3,
        'warmup_steps':10,
        'wd':0.01,
        'arch':'v2.0', #'rnakinet' (default) or 'rnakinet_lastonly' (different rnn pooling method)
        'arch_hyperparams':{},
        'grad_acc':1,
        'early_stopping_patience':5, 
        'wandb_project_name':'RNAkinet_dummy',
        'logging_step':10000,
        'enable_progress_bar':'no', #set to yes if you want to log training progress bar
        'log_to_file':False, #set to False if you want to log to console, otherwise logged to checkpoints_pl folder
        'valid_read_limit':5000,
    },
    'HB64_sabotage_2_continue': { # HB64_sabotage_2. Try picking up from HB64_PBMC_neg
        'training_positives_exps':  ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_Hek293_5EU_1', '20250612_hsa_dRNA_MCF10A_5EU_1', '20250618_hsa_dRNA_I90_5EU_1', '20250528_mmu_dRNA_3T3_5EU_1', '20260122_scs_dRNA_yeast_dmso_1'],
        'training_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1', '20250529_hsa_dRNA_Hek293_DMSO_1', '20250612_hsa_dRNA_MCF10A_control_1','20250612_hsa_dRNA_I90_control_1', '20240503_hsa_dRNA_HeLa_GFP_24h_NoARS_1','20250528_mmu_dRNA_3T3_DMSO_1', '20260122_scs_dRNA_yeast_5EU_1'],
        'validation_positives_exps' : ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_Hek293_5EU_1', '20250612_hsa_dRNA_MCF10A_5EU_1', '20250618_hsa_dRNA_I90_5EU_1', '20250528_mmu_dRNA_3T3_5EU_1', '20260122_scs_dRNA_yeast_dmso_1'],
        'validation_negatives_exps': ['20250529_hsa_dRNA_HeLa_DMSO_1', '20250529_hsa_dRNA_Hek293_DMSO_1', '20250612_hsa_dRNA_MCF10A_control_1','20250612_hsa_dRNA_I90_control_1', '20240503_hsa_dRNA_HeLa_GFP_24h_NoARS_1','20250528_mmu_dRNA_3T3_DMSO_1', '20260122_scs_dRNA_yeast_5EU_1'],
        'min_len':5000,
        'max_len':400000,
        'skip':5000,
        'workers':32,
        'batch_size':64,
        'sampler':'uniform',
        'lr':1e-4,
        'warmup_steps':100,
        'wd':0.01,
        'arch':'v2.0',
        'arch_hyperparams':{},
        'grad_acc':1,
        'early_stopping_patience':50, 
        'wandb_project_name':'RNAkinet_sabotage',
        'logging_step':10000,
        'enable_progress_bar':'no', 
        'log_to_file':False,
        'valid_read_limit':5000,
        'init_from_checkpoint': 'checkpoints_pl/HB64_PBMC_neg/HB64_PBMC_neg/best-step=2920000-valid_loss=0.37.ckpt',
    },
}

# Can specify path to a trained model here, otherwise Snakemake will automatically use the best checkpoint in CHECKPOINTS_DIR based on the model name in TRAINING_CONFIGS
MODEL_TO_PATH : {
    'HB64_2024_HeLa': 'checkpoints_pl/HB64_2024_HeLa/HB64_2024_HeLa/best-step=1620000-valid_loss=0.37.ckpt',
    'batch_64_multispecies_1': 'checkpoints_pl/batch_64_multispecies_1/batch_64_multispecies_1/best-step=860000-valid_loss=0.48.ckpt',
}
MODEL_INFERENCE_PARAMS : {
    'Hela_batch_64': {
        'batch_size': 64,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'v2.0',
        'threshold': 0.5,
    },
    'Human_batch_64_uniform': {
        'batch_size': 64,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'v2.0',
        'threshold': 0.5,
    },
    'HB64_2024_HeLa': {
        'batch_size': 64,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'v2.0',
        'threshold': 0.5,
    },
    'rnakinet_dev_test': {
        'batch_size': 64,
        'max_len': 100000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'v2.0',
        'threshold': 0.5,
    },
    'HB64_sabotage_2_continue': {
        'batch_size': 64,
        'max_len': 100000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'v2.0',
        'threshold': 0.5,
    },
    'batch_64_multispecies_1': {
        'batch_size': 64,
        'max_len': 400000,
        'min_len': 5000,
        'skip': 5000,
        'threads': 16,
        'arch': 'v2.0',
        'threshold': 0.5,
    },
    
}

INFERENCE_RUN_GROUPS : {
    # Specify a path to each experiment in EXP_TO_PATH. Training and validation splits will be automatically generated based on the REFERENCE_TO_SPLITS configuration.
    'HeLa_NIH_2025':{
        'positives':['20250529_hsa_dRNA_HeLa_5EU_1_TEST'],
        'negatives':['20250529_hsa_dRNA_HeLa_DMSO_1_TEST'],
    },
    'Hek293_NIH_2025':{
        'positives':['20250529_hsa_dRNA_Hek293_5EU_1_TEST'],
        'negatives':['20250529_hsa_dRNA_Hek293_DMSO_1_TEST'],
    },
    'I90_NIH_2025':{
        'positives':['20250618_hsa_dRNA_I90_5EU_1_TEST'],
        'negatives':['20250612_hsa_dRNA_I90_control_1_TEST'],
    },
    'MCF10A_NIH_2025':{
        'positives':['20250612_hsa_dRNA_MCF10A_5EU_1_TEST'],
        'negatives':['20250612_hsa_dRNA_MCF10A_control_1_TEST'],
    },
    '3T3_NIH_2025':{
        'positives':['20250528_mmu_dRNA_3T3_5EU_1_TEST'],
        'negatives':['20250528_mmu_dRNA_3T3_DMSO_1_TEST'],
    },

    #############
    'yeast_NIH_2026_full':{
        'positives':['20260122_scs_dRNA_yeast_5EU_1'],
        'negatives':['20260122_scs_dRNA_yeast_dmso_1'],
    },
    'HeLa_NIH_2025_full':{
        'positives':['20250529_hsa_dRNA_HeLa_5EU_1'],
        'negatives':['20250529_hsa_dRNA_HeLa_DMSO_1'],
    },
    'Hek293_NIH_2025_full':{
        'positives':['20250529_hsa_dRNA_Hek293_5EU_1'],
        'negatives':['20250529_hsa_dRNA_Hek293_DMSO_1'],
    },
    'I90_NIH_2025_full':{
        'positives':['20250618_hsa_dRNA_I90_5EU_1'],
        'negatives':['20250612_hsa_dRNA_I90_control_1'],
    },
    'MCF10A_NIH_2025_full':{
        'positives':['20250612_hsa_dRNA_MCF10A_5EU_1'],
        'negatives':['20250612_hsa_dRNA_MCF10A_control_1'],
    },
    '3T3_NIH_2025_full':{
        'positives':['20250528_mmu_dRNA_3T3_5EU_1'],
        'negatives':['20250528_mmu_dRNA_3T3_DMSO_1'],
    },

}

# HALFLIVES CONFIGURATION
ENSEMBL_URL : 'http://may2025.archive.ensembl.org'

HALFLIVES_NAME_TO_FILE : {
    'mion':'3T3_mion_halflives.csv',
    'PION':'3T3_PION_halflives.csv',
}

PCT_POS_GRAPHING_PARAMS: {
    'graph_title1': {
        'models' : ['Human_batch_64_uniform'],
        'experiments' : ['20250529_hsa_dRNA_HeLa_5EU_1_TEST',],
        'colors' : ['blue', 'orange', 'green'],
        }
}

DIAGNOSTICS_GRAPHING_PARAMS: {
    'graph_title1': {
        'metric': 'mean',
        'experiments': ['20250529_hsa_dRNA_HeLa_5EU_1', '20250529_hsa_dRNA_HeLa_DMSO_1'],
        'subsample': 0.01,
    },   
}