EXP_TO_REFERENCE: {
    '20250529_hsa_dRNA_HeLa_5EU_1':       'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250529_hsa_dRNA_HeLa_DMSO_1':      'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250529_hsa_dRNA_Hek293_5EU_1':     'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250529_hsa_dRNA_Hek293_DMSO_1':    'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250612_hsa_dRNA_MCF10A_5EU_1':     'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250612_hsa_dRNA_MCF10A_control_1': 'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250618_hsa_dRNA_I90_5EU_1':        'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',
    '20250612_hsa_dRNA_I90_control_1':    'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa',

    '20250528_mmu_dRNA_3T3_5EU_1':         'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa',
    '20250528_mmu_dRNA_3T3_DMSO_1':        'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa',
    '20240502_mmu_dRNA_3T3_5EU_400_2_R10': 'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa',
}

EXP_TO_TRANSCRIPTOME : {
    '20240502_mmu_dRNA_3T3_5EU_400_2_R10':  'Mus_musculus.GRCm39.cdna.all.fa',
}

# Further path inside the DATA_DIR
EXP_TO_PATH : {
    '20250529_hsa_dRNA_HeLa_5EU_1': 'experiments_v2/20250529_hsa_dRNA_HeLa_5EU_1/',
    '20250529_hsa_dRNA_HeLa_DMSO_1': 'experiments_v2/20250529_hsa_dRNA_HeLa_DMSO_1/',

    '20250529_hsa_dRNA_Hek293_5EU_1': 'experiments_v2/20250529_hsa_dRNA_Hek293_5EU_1',
    '20250529_hsa_dRNA_Hek293_DMSO_1': 'experiments_v2/20250529_hsa_dRNA_Hek293_DMSO_1',

    '20250611_mml_dRNA_PBMC_5EU_1': 'experiments_v2/20250611_mml_dRNA_PBMC_5EU_1',
    '20250612_mml_dRNA_PBMC_control_1': 'experiments_v2/20250612_mml_dRNA_PBMC_control_1',

    '20250618_hsa_dRNA_I90_5EU_1': 'experiments_v2/20250618_hsa_dRNA_I90_5EU_1',
    '20250612_hsa_dRNA_I90_control_1': 'experiments_v2/20250612_hsa_dRNA_I90_control_1',

    '20250612_hsa_dRNA_MCF10A_5EU_1': 'experiments_v2/20250612_hsa_dRNA_MCF10A_5EU_1',
    '20250612_hsa_dRNA_MCF10A_control_1': 'experiments_v2/20250612_hsa_dRNA_MCF10A_control_1',

    '20250528_mmu_dRNA_3T3_5EU_1': 'experiments_v2/20250528_mmu_dRNA_3T3_5EU_1',
    '20250528_mmu_dRNA_3T3_DMSO_1': 'experiments_v2/20250528_mmu_dRNA_3T3_DMSO_1',

    '20240502_mmu_dRNA_3T3_5EU_400_2_R10': 'experiments_v2/20240502_mmu_dRNA_3T3_5EU_400_2_R10',


    # INFERENCE_RUN_TO_FILES
    # Snakemake will automatically generate the test splits (see data_split.smk) for the experiment paths listed here according to the REFERENCE_TO_SPLITS configuration
    # These splits (or full experiments) can be used in INFERENCE_RUN_GROUPS to generate metrics as desired. Paths should be relative to the DATA_DIR
    '20250529_hsa_dRNA_HeLa_5EU_1_TEST': '../outputs_dev/splits/20250529_hsa_dRNA_HeLa_5EU_1/test.pod5',
    '20250529_hsa_dRNA_HeLa_DMSO_1_TEST': '../outputs_dev/splits/20250529_hsa_dRNA_HeLa_DMSO_1/test.pod5',

    '20250529_hsa_dRNA_Hek293_5EU_1_TEST': '../outputs_dev/splits/20250529_hsa_dRNA_Hek293_5EU_1/test.pod5',
    '20250529_hsa_dRNA_Hek293_DMSO_1_TEST': '../outputs_dev/splits/20250529_hsa_dRNA_Hek293_DMSO_1/test.pod5',

    '20250618_hsa_dRNA_I90_5EU_1_TEST': '../outputs_dev/splits/20250618_hsa_dRNA_I90_5EU_1/test.pod5',
    '20250612_hsa_dRNA_I90_control_1_TEST': '../outputs_dev/splits/20250612_hsa_dRNA_I90_control_1/test.pod5',

    '20250612_hsa_dRNA_MCF10A_5EU_1_TEST': '../outputs_dev/splits/20250612_hsa_dRNA_MCF10A_5EU_1/test.pod5',
    '20250612_hsa_dRNA_MCF10A_control_1_TEST': '../outputs_dev/splits/20250612_hsa_dRNA_MCF10A_control_1/test.pod5',
    
    '20250528_mmu_dRNA_3T3_5EU_1_TEST': '../outputs_dev/splits/20250528_mmu_dRNA_3T3_5EU_1/test.pod5',
    '20250528_mmu_dRNA_3T3_DMSO_1_TEST': '../outputs_dev/splits/20250528_mmu_dRNA_3T3_DMSO_1/test.pod5',
}

EXP_TO_ENSEMBL_SPECIES : {
    '20240502_mmu_dRNA_3T3_5EU_400_2_R10':'mmusculus',
}
EXP_TO_TL : {
    '20240502_mmu_dRNA_3T3_5EU_400_2_R10': 2,
}

